version: '3.7'
services:
  es:
    build:
      context: ./devops/elk/es
      args:
        VERSION: 7.17.9
    container_name: es
    environment:
      - node.name=single-node
      - cluster.name=backtony
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-bridge

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.9
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - es-bridge

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash-oss:7.17.9
    hostname: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTICSEARCH_HOSTS: http://es:9200
    build:
      context: ./devops/elk/logstash
    volumes:
      - ./devops/elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./devops/elk/logstash/pipeline:/usr/share/logstash/pipeline
      - ./devops/elk/logstash/mysql-connector-java-5.1.46.jar:/usr/share/logstash/mysql-connector-java-5.1.46.jar
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    networks:
      - es-bridge
    depends_on:
      - es

networks:
  es-bridge:
    driver: bridge