spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 64646017439-jam31jpdjm0aqu94fcc22nqrn6tv19l9.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://ec2-54-180-131-152.ap-northeast-2.compute.amazonaws.com:8080/oauth2/callback/google
            scope:
              - profile
              - email
          naver:
            client-id: Div9n6TQIlgSqnBFke1V
            client-secret: LXm6QR_iUW
            scope:
              - name
              - email
              - image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://ec2-54-180-131-152.ap-northeast-2.compute.amazonaws.com:8080/api/oauth2/callback/naver
          kakao:
            client-id: 320c9a9b26042288264956f598de9d78 # rest api key
            client-secret: UJNDHowcPllj7iggLg68smnz0ApAwD3H
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://ec2-54-180-131-152.ap-northeast-2.compute.amazonaws.com:8080/api/oauth2/callback/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


app:
  oauth2:
    authorizedRedirectUri: http://ec2-54-180-131-152.ap-northeast-2.compute.amazonaws.com:8080/api/oauth2/authorize/redirect